backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"  # Ensure this name is unique and not duplicated in any other config file
    label: "Posts"
    folder: "src/posts"  # Folder where your post content is stored
    create: true  # Allow new posts to be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Slug format for new posts
    fields:
      - { label: "Title", name: "title", widget: "string" }  # Title field for each post
      - { label: "Publish Date", name: "date", widget: "datetime" }  # Publish date for each post
      - { label: "Body", name: "body", widget: "markdown" }  # Markdown body content for each post
