name: Deploy 11ty to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build site with 11ty
        run: npm run build

      - name: Set up Git for Deployment
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
        
      - name: Create gh-pages branch if not exists
        run: |
          git fetch
          git checkout -B gh-pages

      - name: Pull remote changes from gh-pages
        run: |
          git pull origin gh-pages --rebase || echo "No changes to pull"

      - name: Add _site files to gh-pages branch
        run: |
          # Ensure we add only the files from the _site directory
          git add -f _site/*
        
      - name: Commit and push changes to gh-pages
        run: |
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
