name: Deploy 11ty to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build site with 11ty
        run: npm run build

      - name: Set up Git for Deployment
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create or switch to gh-pages branch
        run: |
          git fetch
          git checkout -B gh-pages

      - name: Remove old content from gh-pages branch
        run: |
          git rm -rf . || echo "No files to remove"

      - name: Copy built site to root of gh-pages
        run: |
          cp -r _site/* ./

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"

      - name: Push changes to gh-pages branch
        run: git push origin gh-pages --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
